<?php
// generated by Poedit from wp-rijkshuisstijl-nl_NL.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'nl_NL','pot-creation-date'=>'2026-02-16 16:02+0100','po-revision-date'=>'2026-02-16 16:02+0100','translation-revision-date'=>'2026-02-16 16:02+0100','project-id-version'=>'ICTU / Digitale Overheid / Community','x-generator'=>'Poedit 3.8','messages'=>['Update options'=>'Update options']];
